In [1]:
import numpy as np

In [3]:
p = np.load('train_x.npy')

In [4]:
import pandas as pd

In [5]:
p= pd.DataFrame(p)

In [6]:
p

,0,1,2,3,4,5,6,7,8,9,...,22,23,24,25,26,27,28,29,30,31
0,3.0,62.0,3.0,12.0,17.6926,212.3110,12.05210,52.666667,58.000000,5.000000,...,13.106667,105.333333,2.564300,6.615800,6.851867,4.040910,476.000000,31.066667,394.666667,44522.666667
1,7.0,229.0,1.0,1.0,31.2849,31.2849,11.09230,83.000000,87.000000,6.000000,...,21.310000,8.000000,1.500000,42.676700,3.397200,2.671040,207.000000,10.900000,160.000000,90526.000000
2,7.0,225.0,3.0,9.0,46.5516,418.9640,4.16578,49.111111,75.888889,5.000000,...,31.347778,20.632667,1.545833,122.714767,4.134178,2.806147,122.888889,6.437778,62.155556,28734.888889
3,4.0,140.0,3.0,12.0,22.8710,274.4510,7.26211,42.666667,77.833333,4.666667,...,14.555000,91.333333,1.256250,40.077133,3.701017,2.533433,334.333333,10.400000,311.333333,23370.000000
4,6.0,194.0,2.0,6.0,28.3409,170.0460,10.33890,71.000000,42.000000,6.000000,...,18.413333,22.666667,1.880967,37.157967,4.260000,3.088953,254.000000,8.800000,241.666667,64369.333333
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
4932,3.0,62.0,2.0,8.0,26.0533,208.4260,5.32170,35.500000,59.000000,4.500000,...,17.225000,81.500000,1.108300,127.859550,4.076600,2.544890,443.500000,28.200000,379.500000,20382.000000
4933,4.0,127.0,3.0,8.0,28.9976,231.9810,5.64035,41.500000,66.500000,4.500000,...,22.247500,105.260000,2.147375,54.442200,6.095000,3.542505,227.750000,6.407500,114.725000,27412.350000
4934,6.0,194.0,2.0,4.0,21.9549,87.8198,4.79746,28.000000,72.000000,4.000000,...,13.530000,11.260000,1.364900,37.805450,4.636700,2.725210,349.000000,12.050000,225.500000,8812.000000
4935,7.0,221.0,2.0,4.0,16.8143,67.2572,14.76030,60.000000,55.500000,5.000000,...,10.912500,261.250000,3.341075,6.275275,8.302600,4.886832,315.750000,10.125000,284.250000,60557.425000
4936,6.0,194.0,2.0,8.0,23.1516,185.2130,1.79210,12.000000,30.750000,3.000000,...,22.090000,105.059000,0.949975,35.343125,4.302950,2.484618,159.000000,2.110000,76.375000,1339.475000